sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - echo "127.0.0.1  nc.network.local" | sudo tee -a /etc/hosts
  - echo "127.0.0.1  wp.network.local" | sudo tee -a /etc/hosts
  - echo "127.0.0.1  pma.network.local" | sudo tee -a /etc/hosts
  - docker-compose -f ./Nextcloud-Wordpress/docker-compose.yml up -d
  - sleep 30

script: ./scripts/test.sh

after_script:
  - docker rm -f $(docker ps -a -q)
  - docker volume prune -f